query insumos($id: ID!) {
  categoryInsumos(where: { id: $id }) {
    categoryname
    insumos(sort: "nombre_empresa:asc") {
      id
      nombre_empresa
      website
      descripcion
      latitud
      longitud
      telefono
      logo {
        url
      }
    }
  }
}
