query servicios($id: ID!) {
  categoryServicios(where: { id: $id }) {
    categoria
    servicios(sort: "nombre:asc", where: { aprobado: true }) {
      id
      nombre
      web
      telefono
      ciudad
      direccion
      web_catalogo
      resumen_descripcion
      aprobado
      imagen_servicio {
        url
      }
      category_servicio {
        categoria
      }      
    }
  }
}
