query servicioByUserId($id: ID!) {
  servicios(where: { users: { id: $id } }) {
    id
    nombre
    telefono
    resumen_descripcion
    web
    web_catalogo
    aprobado
    ciudad
    direccion
    observacion
    email
    imagen_servicio {
      id
    }
    category_servicio {
      id
    }
  }
}
